language: csharp
mono: none
dotnet: 2.1.4
os: linux
dist: trusty
sudo: false
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
  - ./build.sh
  
deploy:
  - provider: script
    script: ./deploy-branch.sh
    on:
      branch: master
  - provider: script
    script: ./deploy-tag.sh
    on:
      tags: true